#!/usr/bin/env bash
# nginx web server listening on port 80
# returns a page that contains the string "Hello World!"
# Update package list
apt-get update

# Install nginx
apt-get install -y nginx

# Start nginx
service nginx start

# Create a default HTML file
echo "Hello World!" > /var/www/html/index.html

# Check if nginx is running
if pgrep -x "nginx" 
then
    echo "Nginx is running."
else
    echo "Error: Nginx is not running."
fi

