#!/usr/bin/env bash
# sets up a new 404 error page

# Update package list
apt-get update

# Install nginx
apt-get install -y nginx

# Start nginx
service nginx start

# Create a default HTML file
echo "Hello World!" > /var/www/html/index.html

# Create a custom configuration for redirection
echo "
server {
    listen 80;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        root /var/www/html;
        index index.html;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Create a custom 404 HTML file
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Reload nginx to apply the new configuration
service nginx reload
